version: 2.7.1
slug: mariadb
name: MariaDB
description: A SQL database server
url: https://github.com/Vioneta/addons/tree/master/mariadb
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
backup_post: unlock-tables-for-backup
backup_pre: lock-tables-for-backup
image:
- vioneta/{arch}-addon-mariadb
- ghcr.io/vioneta/{arch}-addon-mariadb
init: false
options:
  databases:
  - vioneta
  logins:
  - password: null
    username: vioneta
  rights:
  - database: vioneta
    username: vioneta
ports:
  3306/tcp: null
schema:
  databases:
  - str
  logins:
  - username: str
    password: password
  rights:
  - database: str
    privileges:
    - "list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|CREATE VIEW|DELETE|DELETE HISTORY|DROP|EVENT|GRANT OPTION|INDEX|INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?"
    username: str
services:
- mysql:provide
startup: system
timeout: 300
