arch:
- aarch64
- amd64
- armv7
backup: cold
description: Postgres 15 with pgvecto.rs support
environment:
  CONFIG_LOCATION: "/config/postgresql.conf"
  PGDATA: "/config/database"
image:
- ghcr.io/vioneta/postgres-{arch}
- vioneta/postgres-{arch}
map:
- addon_config:rw
- homeassistant_config:rw
- media:rw
name: Postgres 15
options:
  POSTGRES_PASSWORD: vioneta
ports:
  5432/tcp: 5432
ports_description:
  5432/tcp: Postgres
schema:
  POSTGRES_DB: str?
  POSTGRES_HOST_AUTH_METHOD: str?
  POSTGRES_INITDB_ARGS: str?
  POSTGRES_PASSWORD: str
  POSTGRES_USER: str?
slug: postgres
udev: true
url: https://github.com/Vioneta/addons
version: 15.5-7
